FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY public ./public
COPY .next/static ./.next/static
COPY .next/standalone ./

EXPOSE 3000
CMD ["node", "server.js"]
